@ECHO OFF
SET TEMP=C:\
SET TMP=C:\
PATH=A:\
LH MSCDEX.EXE /D:oemcd001 /L:X
IF NOT EXIST X:\WIN95\SETUP.EXE GOTO NOCD
X:\WIN95\SETUP.EXE C:\MSBATCH.INF /IS /IQ /IM /ID /IE /IW
GOTO END
:NOCD
ECHO Windows 95 installation CD was not found on drive X:.
:END
